[package]
name = "rusty-goban"
version = "0.1.0"
authors = ["Dylan Wilson <dylanjw@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "rusty-goban"
path = "src/main.rs"
